# Generated by Django 5.2.8 on 2025-12-03 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('photography', 'Photography'), ('fashion_design', 'Fashion Design'), ('modeling', 'Modeling'), ('styling', 'Styling'), ('makeup_artistry', 'Makeup Artistry'), ('tailoring', 'Tailoring'), ('other', 'Other')], max_length=50)),
                ('location', models.CharField(max_length=225)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
