from django.core.mail import send_mail
from .models import User


def send_verification_mail(user_id: int, code: str) -> None:
    """Send a one-time verification code to the user's email.

    The code is generated by the caller to ensure uniqueness per request.
    """
    try:
        user = User.objects.get(id=user_id)
    except User.DoesNotExist:
        raise ValueError("User doesn't exist")

    send_mail(
        subject="Verify Your Email",
        message=f"Your verification code is: {code}",
        from_email="no-reply@fashioncommerce.com",
        recipient_list=[user.email],
        fail_silently=False,
    )


def send_reset_password_mail(user_id: int, code: str) -> None:
    """Send a one-time password reset code to the user's email."""
    try:
        user = User.objects.get(id=user_id)
    except User.DoesNotExist:
        raise ValueError("User doesn't exist")

    send_mail(
        subject="Password reset OTP",
        message=f"Your password reset code: {code}",
        from_email="no-reply@fashioncommerce.com",
        recipient_list=[user.email],
        fail_silently=False,
    )